=== vectorflow/vantage-bot/assets/modules/channel-web/config.schema.json
{
  "type": "object",
  "properties": {
    "uploadsUseS3": {
      "default": false,
      "type": "boolean"
    },
    "uploadsS3Bucket": {
      "default": "bucket-name",
      "type": "string"
    },
    "uploadsS3Region": {
      "default": "eu-west-1",
      "type": "string"
    },
    "uploadsS3AWSAccessKey": {
      "default": "your-aws-key-name",
      "type": "string"
    },
    "uploadsS3AWSAccessSecret": {
      "default": "secret-key",
      "type": "string"
    },
    "startNewConvoOnTimeout": {
      "default": false,
      "type": "boolean"
    },
    "recentConversationLifetime": {
      "default": "6 hours",
      "type": "string"
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== vectorflow/vantage-bot/data/global/config/channel-web.json
{
  "$schema": "../../../assets/modules/channel-web/config.schema.json",
  "uploadsUseS3": false,
  "uploadsS3Bucket": "bucket-name",
  "uploadsS3Region": "eu-west-1",
  "uploadsS3AWSAccessKey": "your-aws-key-name",
  "uploadsS3AWSAccessSecret": "secret-key",
  "startNewConvoOnTimeout": false,
  "recentConversationLifetime": "6 hours"
}
